title: 我的个人成长小网站
description: 学习笔记、日常杂谈、兴趣记录合集
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
heading_anchors: true
footer_content: "个人记录小站 | 持续更新中"
nav_sort: case_sensitive
include:
  - "*.html"
stylesheets:
  - "/assets/css/custom.scss"
